# Generated by Django 5.2.7 on 2026-03-10 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text="Nom officiel de l'entreprise", max_length=200, verbose_name="Nom de l'entreprise")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='entreprises/logos/', verbose_name="Logo de l'entreprise")),
                ('description', models.TextField(blank=True, help_text="Présentation de l'entreprise", null=True, verbose_name='Description')),
                ('savoir_faire', models.JSONField(blank=True, help_text="Compétences ou services offerts par l'entreprise", null=True, verbose_name='Savoir-faire')),
                ('website', models.URLField(blank=True, help_text='URL du site officiel', null=True, verbose_name='Site Web')),
                ('actif', models.BooleanField(default=True, help_text="Si l'entreprise est active ou désactivée", verbose_name='Entreprise active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création du profil')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_entreprise', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('fabricant', models.CharField(blank=True, max_length=255, null=True)),
                ('marque', models.CharField(blank=True, max_length=255, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remise', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('commandes', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('Published', 'Published'), ('Scheduled', 'Scheduled'), ('Draft', 'Draft')], default='Published', max_length=50)),
                ('visibilite', models.CharField(choices=[('Public', 'Public'), ('Hidden', 'Hidden')], default='Public', max_length=50)),
                ('categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_titre', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_mots_cles', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entreprise.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('date_commande', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adresse_livraison', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.client')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entreprise.entreprise')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entreprise.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_validation', models.DateField(auto_now_add=True)),
                ('code_validation_entreprise', models.CharField(max_length=10)),
                ('code_validation_client', models.CharField(max_length=10)),
                ('code_validation_livreur', models.CharField(blank=True, max_length=10, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.client')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entreprise.commande')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entreprise.entreprise')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
    ]
