<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-29 20:37
=======
# Generated by Django 5.2.7 on 2025-11-03 21:32
>>>>>>> 1c872f7ba735c31c2d4b9434f045b31a43134a2f

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
        ('Livreur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/entreprise_logos/')),
                ('description', models.TextField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/produit_images/')),
                ('categorie', models.CharField(max_length=100)),
                ('sous_categorie', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=100)),
                ('couleur', models.CharField(max_length=50)),
                ('taille', models.CharField(max_length=20)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponibilite', models.BooleanField(default=True)),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entreprise.entreprise')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('date_commande', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adresse_livraison', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.client')),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Livreur.livreur')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entreprise.entreprise')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entreprise.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_validation', models.DateField(auto_now_add=True)),
                ('code_validation_entreprise', models.CharField(max_length=10)),
                ('code_validation_client', models.CharField(max_length=10)),
                ('code_validation_livreur', models.CharField(blank=True, max_length=10, null=True)),
                ('Entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entreprise.entreprise')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.client')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entreprise.commande')),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Livreur.livreur')),
                ('partenaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partenaires', to='Client.client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
    ]
