# Generated by Django 5.2.7 on 2026-03-10 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Entreprise', '0001_initial'),
        ('Livreur', '0001_initial'),
        ('Partenaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Livreur.livreur'),
        ),
        migrations.AddField(
            model_name='validation',
            name='partenaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partenaires', to='Partenaire.partenaire'),
        ),
    ]
