# Generated by Django 5.2.7 on 2026-03-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entreprise', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='designation',
            field=models.CharField(blank=True, help_text="Nom officiel de l'entreprise", max_length=200, null=True, unique=True, verbose_name="Nom de l'entreprise"),
        ),
    ]
