# Generated by Django 5.2.7 on 2026-03-10 23:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('client', 'Client'), ('livreur', 'Livreur'), ('entreprise', 'Entreprise'), ('partenaire', 'Partenaire'), ('admin', 'Administrateur'), ('super_admin', 'Super Administrateur'), ('correspondant', 'Correspondant')], db_index=True, default='client', max_length=20)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('nom', models.CharField(blank=True, max_length=150, null=True)),
                ('prenom', models.CharField(blank=True, max_length=150, null=True)),
                ('telephone', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('pays', models.CharField(blank=True, max_length=50, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('profil', models.ImageField(blank=True, null=True, upload_to='users/profils/')),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('homme', 'Homme'), ('femme', 'Femme')], max_length=10, null=True)),
                ('email_verifie', models.BooleanField(default=False)),
                ('telephone_verifie', models.BooleanField(default=False)),
                ('code_verification', models.CharField(blank=True, max_length=6, null=True)),
                ('code_expiration', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('en_attente', 'En attente')], default='en_attente', max_length=20)),
                ('raison_suspension', models.TextField(blank=True, null=True)),
                ('note', models.FloatField(default=0)),
                ('nombre_avis', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('est_en_ligne', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, help_text="Accès à l'administration Django")),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
        ),
    ]
