# Generated by Django 5.2.7 on 2025-10-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de famille du partenaire.', max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(help_text='Prénom du partenaire.', max_length=100, verbose_name='Prénom')),
                ('pseudo', models.CharField(help_text='Nom unique utilisé pour se connecter.', max_length=50, unique=True, verbose_name="Nom d'utilisateur (pseudo)")),
                ('mail', models.EmailField(help_text='Adresse mail utilisée pour la connexion et la communication.', max_length=254, unique=True, verbose_name='Adresse e-mail')),
                ('profil', models.ImageField(blank=True, help_text='Image représentant le partenaire (facultative).', null=True, upload_to='profils_partenaire/', verbose_name='Photo de profil')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], help_text='Sexe du partenaire : M ou F.', max_length=1, verbose_name='Genre')),
                ('date_naissance', models.DateField(help_text='Date de naissance du partenaire.', verbose_name='Date de naissance')),
                ('mot_de_passe', models.CharField(help_text="Mot de passe chiffré pour l'accès au compte.", max_length=255, verbose_name='Mot de passe')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création du compte')),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['-date_creation'],
            },
        ),
    ]
