# Generated by Django 5.2.7 on 2026-03-10 23:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID pour le lien sécurisé de confirmation')),
                ('code_verification', models.CharField(blank=True, help_text='Code numérique de 6 chiffres pour vérification par email ou SMS', max_length=6, null=True)),
                ('compte_confirme', models.BooleanField(default=False)),
                ('token_expiration', models.DateTimeField(blank=True, null=True)),
                ('vehicule', models.CharField(blank=True, max_length=100, null=True)),
                ('zone_livraison', models.CharField(blank=True, max_length=150, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('actif', 'Actif'), ('suspendu', 'Suspendu')], db_index=True, default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Livreur',
                'verbose_name_plural': 'Livreurs',
                'ordering': ['-date_creation'],
            },
        ),
    ]
