# Generated by Django 5.2.7 on 2025-11-03 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livreur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livreur',
            name='identifiant',
            field=models.CharField(help_text="Identifiant unique utilisé pour l'identifié.", max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Identifiant'),
        ),
    ]
