# Generated by Django 5.2.7 on 2026-03-10 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Entreprise', '0002_initial'),
        ('Livreur', '0001_initial'),
        ('Localisation', '0001_initial'),
        ('Partenaire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='code_livreur',
            field=models.OneToOneField(blank=True, help_text='Code unique de création du livreur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livreur', to='Localisation.code_creation'),
        ),
        migrations.AddField(
            model_name='livreur',
            name='createur',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a créé ce livreur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livreurs_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livreur',
            name='entreprise',
            field=models.ForeignKey(blank=True, help_text='Entreprise à laquelle appartient le livreur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livreurs', to='Entreprise.entreprise'),
        ),
        migrations.AddField(
            model_name='livreur',
            name='partenaire',
            field=models.ForeignKey(blank=True, help_text='Partenaire auquel appartient le livreur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livreurs', to='Partenaire.partenaire'),
        ),
        migrations.AddField(
            model_name='livreur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_livreur', to=settings.AUTH_USER_MODEL),
        ),
    ]
