# Generated by Django 5.2.7 on 2025-11-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livreur', '0002_alter_livreur_identifiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livreur',
            name='date_embauche',
            field=models.DateField(blank=True, null=True, verbose_name="Date de l'embauche"),
        ),
    ]
